name: 'Setup Trace'
description: Add the Trace tool to the environment
author: Andy Sammalmaa
branding:
  icon: activity
  color: blue

inputs:
  version:
    description: The release version number to use.  Defaults to latest.
    default: ""
    required: false

outputs:
  tool-path:
    description: The absolute path to trace
    value: ${{ steps.setup.outputs.absolute_path }}

runs:
  using: composite
  steps:
  - id: setup
    shell: sh
    run: |
      ./action.sh "${{ inputs.version }}"
