version: "3"
services:

  jaeger:
    image: jaegertracing/all-in-one:1.38
    ports:
      - "16686:16686"

  collector:
    image: otel/opentelemetry-collector:0.61.0
    ports:
      - "4317:4317"
    volumes:
      - ./collector.yml:/etc/otel/config.yml
    command:
      - "--config"
      - "/etc/otel/config.yml"
    depends_on:
      - jaeger
