name: Build

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: "0"
    
    - uses: actions/setup-go@v6
      with:
        go-version-file: "./go.mod"

    - name: Download Modules
      run: go mod download

    - name: Generate
      run: go generate ./...

    - name: Build
      env:
        GOOS: linux
        GOARCH: amd64
        CGO_ENABLED: "0"
      run: go build -ldflags="-X trace/version.GitCommit=${{ github.sha }} -X trace/version.Prerelease="""

    - name: Start Jaeger Stack
      uses: hoverkraft-tech/compose-action@v2

    - name: Test
      run: go test -v ./...

    - name: Run Example
      env:
        OTEL_EXPORTER_OTLP_INSECURE: true
      run: |
        cd example/basic
        ./build.sh

        traceid=$(cut -d"-" -f2 ".traceid")
        jaeger_url="http://localhost:16686/api/traces/${traceid}?prettyPrint=true"

        curl "${jaeger_url}" -o "trace.json"

    - name: Store Trace Binary
      uses: actions/upload-artifact@v6
      with:
        name: trace
        path: trace

    - name: Store Trace Json
      uses: actions/upload-artifact@v6
      with:
        name: trace.json
        path: example/basic/trace.json

    - name: Generate Release Notes
      run: |
        echo "TRACE_VERSION=$(./trace version --short)" >> "${GITHUB_ENV}"
        ./trace version --changelog --raw | tee release-notes.md

    - name: Check if Changelog has changed
      uses: dorny/paths-filter@v4
      id: changes
      with:
        filters: |
          changelog:
            - 'changelog.md'

    - name: Release
      if: ${{ github.ref_name == 'main' && steps.changes.outputs.changelog == 'true' }}
      uses: softprops/action-gh-release@v2
      with:
        name: ${{ env.TRACE_VERSION }}
        tag_name: ${{ env.TRACE_VERSION }}
        body_path: release-notes.md
        files: trace
        overwrite_files: false
